.DEFAULT_GOAL := help
COMPOSE := docker compose
BACKEND := cd backend &&

.PHONY: help
help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'

.PHONY: install
install: ## Install backend dev dependencies
	$(BACKEND) pip install -e ".[dev]"

.PHONY: dev
dev: ## Run the full stack via docker compose
	$(COMPOSE) up --build

.PHONY: up
up: ## Start stack in background
	$(COMPOSE) up -d --build

.PHONY: down
down: ## Stop stack
	$(COMPOSE) down

.PHONY: migrate
migrate: ## Apply Alembic migrations
	$(BACKEND) alembic upgrade head

.PHONY: revision
revision: ## Create a new autogenerated migration (msg="...")
	$(BACKEND) alembic revision --autogenerate -m "$(msg)"

.PHONY: test
test: ## Run backend tests
	$(BACKEND) pytest -q

.PHONY: lint
lint: ## Run ruff + mypy
	$(BACKEND) ruff check src tests
	$(BACKEND) ruff format --check src tests
	$(BACKEND) mypy src

.PHONY: fmt
fmt: ## Auto-format code
	$(BACKEND) ruff check --fix src tests
	$(BACKEND) ruff format src tests

.PHONY: psql
psql: ## Open psql against the compose database
	$(COMPOSE) exec postgres psql -U ytkb -d ytkb
